branches:
  except:
    - gh-pages

language: python

install: "pip install -r requirements.txt"

script: 
  - coverage run --source=Cryptsy.py -m py.test test_cryptsy.py -v
  - coverage report -m

after_script:
  - coveralls --verbose
